# Generated by Django 2.0.2 on 2018-02-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='test',
            field=models.CharField(max_length=20),
        ),
    ]
