# Generated by Django 2.0.2 on 2018-02-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20180210_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='test2',
            name='dff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='test2',
            name='test',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
