# Generated by Django 2.0.2 on 2018-02-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_auto_20180210_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='limit',
        ),
    ]
